#
# Solution to Project Euler problem 2
# Even Fibonacci numbers
#

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

def fib_gen(max_val=None):
    a, b = 0, 1
    while not max_val or a < max_val:
        yield a
        a, b = b, a + b


def even_fib_sum(max_val):
    return sum([i for i in fib_gen(max_val) if i % 2 == 0])


def solve():
    return str(even_fib_sum(4_000_000))


if __name__ == "__main__":
    print(solve())
