# 
# Solution to Project Euler problem 2
# Even Fibonacci numbers
# 

# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.


def is_multiple_3_or_5(num):
	return sum([x for x in range(num) if x % 3 == 0 or x % 5 == 0])

def solve():
	return str(is_multiple_3_or_5(1000))

if __name__ == "__main__":
	print(solve())